from .api_key_node   import NODE_CLASS_MAPPINGS as API_KEY_NODES,    NODE_DISPLAY_NAME_MAPPINGS as API_KEY_NAMES
from .text_to_image  import NODE_CLASS_MAPPINGS as T2I_NODES,         NODE_DISPLAY_NAME_MAPPINGS as T2I_NAMES
from .image_to_image import NODE_CLASS_MAPPINGS as I2I_NODES,         NODE_DISPLAY_NAME_MAPPINGS as I2I_NAMES
from .multi_image    import NODE_CLASS_MAPPINGS as MULTI_NODES,       NODE_DISPLAY_NAME_MAPPINGS as MULTI_NAMES
from .text_to_video  import NODE_CLASS_MAPPINGS as T2V_NODES,         NODE_DISPLAY_NAME_MAPPINGS as T2V_NAMES
from .image_to_video import NODE_CLASS_MAPPINGS as I2V_NODES,         NODE_DISPLAY_NAME_MAPPINGS as I2V_NAMES
from .video_save     import NODE_CLASS_MAPPINGS as VIDEO_SAVE_NODES,  NODE_DISPLAY_NAME_MAPPINGS as VIDEO_SAVE_NAMES
from .seedream_node  import NODE_CLASS_MAPPINGS as SEEDREAM_NODES,    NODE_DISPLAY_NAME_MAPPINGS as SEEDREAM_NAMES

NODE_CLASS_MAPPINGS = {
    **API_KEY_NODES,
    **T2I_NODES,
    **I2I_NODES,
    **MULTI_NODES,
    **T2V_NODES,
    **I2V_NODES,
    **VIDEO_SAVE_NODES,
    **SEEDREAM_NODES,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **API_KEY_NAMES,
    **T2I_NAMES,
    **I2I_NAMES,
    **MULTI_NAMES,
    **T2V_NAMES,
    **I2V_NAMES,
    **VIDEO_SAVE_NAMES,
    **SEEDREAM_NAMES,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
